// This file is automatically generated by vscode-react-native@0.2.5
// Please do not modify it manually. All changes will be lost.
try {
    var path = require("path");
    var Launcher = require("/Users/tujiaw/.vscode/extensions/vsmobile.vscode-react-native-0.2.5/out/debugger/launcher.js").Launcher;
    new Launcher("/Users/tujiaw/Documents/github/rndog/cndog", "/Users/tujiaw/Documents/github/rndog/cndog").launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}